date = 09/02/2026
time = 18:43
notes = "This config is used for the optimisation of the pulse shapes"

waveform sequence = "[0],[1],[2]"
waveform stitch delays = "[-1,[]],[-1,[]], [-1,[]]"
interleave waveforms = True
sample rate = 1.25e9
burst count = 1
waveform output channels = channel1, channel2, channel3
waveform output channel lags = 0.0, 0.0, 0.0 # delay in micro seconds
marked channels = channel1, channel2, channel3
marker width = 0.1


[waveforms]
[[0]]
modulation frequency = 60.855800e6 
phases = ,
filename = waveforms\marina\zeros\zero_10.csv

[[1]]
modulation frequency = 74e6
# or 80e6 for STIRAP
phases = ,
filename = waveforms\marina\zeros\zero_10.csv
# or waveforms\pulse_shaping_exp\stirap\standard_200ns_stokes.csv for STIRAP

[[2]]
modulation frequency = 54.855800e6
phases = ,
filename = waveforms\marina\zeros\zero_10.csv
