date = 26/01/2026
time = 18:54
notes = "THE NUMBERS LABELLING EACH OF THE PULSES MUST BE ACCURATE This awg config is for the new experimental sequence with optical pumping into |F=2, m=2>  followed by STIRAP transfer to |F=1, m=1>. Channel 1: EYLSA STIRAP Channel 2: DL Pro optical pumping and STIRAP Channel 3: EYLSA optical pumping"

waveform sequence = "[2, 3],[0, 4],[1]"
waveform stitch delays = "[-1,[]],[-1,[]], [-1,[]]"
interleave waveforms = True
sample rate = 1000000000.0
burst count = 1
waveform output channels = channel1, channel2, channel3
waveform output channel lags = 0.015, 0, 0
marked channels = channel1, channel2, channel3
marker width = 0.1


[waveforms]
[[0]]
# F=1 opt pump (ch2)
modulation frequency = 74000000 
phases = ,
filename = waveforms\new_Jan\tophat\tophat_1000ns.csv

[[1]]
# F=2 opt pump (ch3)
modulation frequency = 54855800
phases = ,
filename = waveforms\new_Jan\tophat\tophat_1000ns.csv

[[2]]
# ch1 wait
modulation frequency = 0
phases = ,
filename = waveforms\marina\zeros\zero_1000.csv

[[3]]
# F=2 STIRAP pump pulse
modulation frequency = 60855800
phases = ,
filename = waveforms\pulse_shaping_exp\stirap\standard_200ns_pump.csv

[[4]]
# F=1 STIRAP Stokes pulse
modulation frequency = 80000000
phases = ,
filename = waveforms\pulse_shaping_exp\stirap\standard_200ns_stokes.csv


