date = 26/11/2025
time = 16:51


waveform sequence = "[8]"
waveform stitch delays = "[1,[]]"
interleave waveforms = True

[waveforms]
[[8]]
# Ch4 optical pumping
modulation frequency = 0
phases = ,
filename = waveforms/new_Jan/tophat/tophat_1000ns_100.csv



[AWG]
sample rate = 1000000000.0
burst count = 10000
waveform output channels = channel4,
waveform output channel lags = 0
marked channels = channel4,
marker width = 0.1

