date = 05/05/25
time = 18:37

waveform sequence = "[0, 2, 4, 6, 8],[1, 3, 5, 7, 9], [10]"#, [10]"
waveform stitch delays = "[-1,[]],[-1,[]], [-1,[]], [-1,[]]"
interleave waveforms = True

sample rate = 1000000000.0
burst count = 1
waveform output channels = channel1, channel2, channel3#, channel4
waveform output channel lags = 0.015, 0, 0#, 0
marked channels =  channel2,
marker width = 0.1




[waveforms]

# channel 1 waveforms
[[0]]
modulation frequency = 124000000
#124000000
phases = ,
filename = waveforms\new_Jan\tophat\tophat_1000ns.csv

[[1]]
modulation frequency = 0
#80000000
phases = ,
filename = waveforms\pulse_shaping_exp\stirap\sin_700ns.csv

[[2]]
modulation frequency = 0
phases = ,
filename = waveforms\marina\zeros\zero_500.csv

[[3]]
modulation frequency = 0
phases = ,
filename = waveforms\marina\zeros\zero_500.csv

[[4]]
modulation frequency = 124000000
phases = ,
filename = waveforms\new_Jan\tophat\tophat_1000ns.csv

[[5]]
modulation frequency = 0
phases = ,
filename = waveforms\pulse_shaping_exp\stirap\sin_700ns.csv

[[6]]
modulation frequency = 124000000
phases = ,
filename = waveforms\pulse_shaping_exp\stirap\sin_500ns.csv

[[7]]
modulation frequency = 0
phases = ,
filename = waveforms\marina\zeros\zero_500.csv

[[8]]
modulation frequency = 124000000
phases = ,
filename = waveforms\pulse_shaping_exp\stirap\sin_700ns.csv

[[9]]
modulation frequency = 0
phases = ,
filename = waveforms\pulse_shaping_exp\stirap\sin_700ns.csv


# channel 3 waveforms
[[10]]
modulation frequency = 0
phases = ,
filename = waveforms\marina\zeros\zero_1.csv

