[defaults]
extrapolate_policy = clamp

[calibrations]
# Example mappings:
# channel_key = human_name, path/to/calibration.csv
# Use the key that your code will ask for (e.g. ch0, 0, cool_center_amp)
0 = cool_center_amp, calibrations/cool_center/cool_center_abs_amp_at_100MHz.csv
1 = cool_center_freq, calibrations/cool_center/cool_center_amp_at_100MHz.csv
