date = 02/02/2026
time = 17:05
notes = "Experiment config for pulse shaping experiment without camera. Now the oscilloscope channels need to be configured with voltage ranges. This sets the maximum and minimum voltages for each channel. Ensure that the range for the trigger channel includes both the lower and upper trigger levels, otherwise triggering may fail."

save location = "C:\pulse_shaping_data"
mot reload = 1000
iterations = 7

use_cam = False
use_scope = True
use_awg= True

[scope_settings]
trigger_channel = 1
trigger_level = 1.0
sample_rate = 50e6
time_range = (-2.5e-3, 2.5e-3)
data_channels = {1:(-1.0, 5.0),2:(-1.0, 5.0),3:(-0.004, 0.008)}

[awg_settings]
config_path="configs\pulse_shaping_expt\awg_configs\test_awg_config.ini"
#"configs\pulse_shaping_expt\awg_configs\ch1_2_config.ini"
config_path_single=""

[metadata]
experiment_type = "MOT Fluorescence"