notes = "Testing how the MOT fluorescence varies with pumping/STIRAP into different states. Sweep 0: no pulses Sweep 1: optical pumping into |F=2, m=2> Sweep 2: Optical pumping into |F=1> Sweep 3: optical pumping into |F=2, m=2> followed by STIRAP into |F=1, m=1>"

save location = "C:\pulse_shaping_data"
mot reload = 1000
iterations = 7

num_shots = 1
sweep_type = "awg_sequence"

sequence_config = "configs\pulse_shaping_expt\sequence\readout_with_MOTC.ini"
scope_config = "configs\pulse_shaping_expt\scope\keysight_feb26.ini"
awg_config = "configs\pulse_shaping_expt\awg_configs\feb26_awg_updated.ini"

[metadata]
config_type = experiment
experiment_type = "MOT Fluorescence Sweep"

[defaults]
waveform_indices = 0, 1, 2, 3, 4
rabi_frequencies = 0, 0, 0, 0, 0
modulation_frequencies = 74e6, 54.8558e6, 60.8558e6, 60.8558e6, 80e6
waveforms = "waveforms\new_Jan\tophat\tophat_1000ns.csv", "waveforms\new_Jan\tophat\tophat_1000ns.csv", "waveforms\marina\zeros\zero_1000.csv", "waveforms\pulse_shaping_exp\stirap\standard_700ns_pump.csv", "waveforms\pulse_shaping_exp\stirap\standard_700ns_stokes.csv"
calibration_paths = "calibrations\pulse_shaping_expt\STIRAP_DL_PRO","calibrations\pulse_shaping_expt\OPT_PUMP_ELYSA", "calibrations\pulse_shaping_expt\STIRAP_ELYSA", "calibrations\pulse_shaping_expt\STIRAP_ELYSA", "calibrations\pulse_shaping_expt\STIRAP_DL_PRO"

[sweeps]
# [[0]]
# title = "no_pulses"


# [[1]]
# title = "pump_to_F2"
# rabi_frequencies = 15, 18, 0, 0, 0



# [[2]]
# title = "pump_to_F1"
# rabi_frequencies = 0, 18, 15, 0, 0
# waveforms = "waveforms\new_Jan\tophat\tophat_1000ns.csv", "waveforms\new_Jan\tophat\tophat_1000ns.csv", "waveforms\new_Jan\tophat\tophat_1000ns.csv", "waveforms\pulse_shaping_exp\stirap\standard_700ns_pump.csv", "waveforms\pulse_shaping_exp\stirap\standard_700ns_stokes.csv"

[[0]]
title = "opt_pump_and_stirap"
rabi_frequencies = 15, 18, 0, 15, 18

